name: Build

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libtirpc-dev
      - name: Bootstrap
        run: ./bootstrap
      - name: Configure
        run: |
          mkdir build
          cd build
          ../configure --prefix=/usr
      - name: Build
        working-directory: build
        run: make
      - name: Install
        working-directory: build
        run: |
          NAME=unfs3-`arch`-g`git rev-parse --short HEAD`
          mkdir $NAME
          make install DESTDIR=`pwd`/$NAME
          tar -acf $NAME.tar.xz $NAME
      - uses: actions/upload-artifact@v4
        with:
          name: Linux (Ubuntu)
          path: build/unfs3-*.tar.xz

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download libtirpc
        run: |
          curl --location --remote-name \
            https://downloads.sourceforge.net/libtirpc/libtirpc-1.3.6.tar.bz2
          tar -xvf libtirpc-1.3.6.tar.bz2
      - name: Build libtirpc
        working-directory: libtirpc-1.3.6
        run: |
          ./configure --prefix=/opt/homebrew
          # FIXME: Upstream botched a macOS fix before release
          echo '#define __APPLE_USE_RFC_3542 1' >> config.h
          make
      - name: Install libtirpc
        working-directory: libtirpc-1.3.6
        run: sudo make install
      - name: Install dependencies
        run: |
          brew install autoconf automake
      - name: Bootstrap
        run: ./bootstrap
      - name: Configure
        run: |
          mkdir build
          cd build
          ../configure --prefix=/usr
      - name: Build
        working-directory: build
        run: make
      - name: Install
        working-directory: build
        run: |
          NAME=unfs3-`arch`-g`git rev-parse --short HEAD`
          mkdir $NAME
          make install DESTDIR=`pwd`/$NAME
          tar -acf $NAME.tar.xz $NAME
      - uses: actions/upload-artifact@v4
        with:
          name: macOS
          path: build/unfs3-*.tar.xz
